"""
Live Actuator — executes mouse/keyboard actions on the real system.

Bridges the gap between synthetic trajectory generation and actual
hardware input.  When running in live mode, this module takes the
movement plans from MouseEmulator and executes them via pynput.

Anti‑ban note: the cognitive engine still drives ALL timing and behaviour.
The actuator just executes what the engine decides — it doesn't add its
own timing.  All delays, misclicks, hovers, etc. come from cognitive.py
and the scenario, not from here.
"""

from __future__ import annotations

import time
import math
from typing import Optional

import numpy as np
from pynput.mouse import Button, Controller as MouseController
from pynput.keyboard import Key, Controller as KeyboardController

from core.mouse import MouseEmulator, MouseSample, ClickEvent
from core.keyboard import KeystrokeEvent


class LiveActuator:
    """
    Executes generated input events on the real system.

    Usage:
        act = LiveActuator()
        act.move_to(800, 400)       # smooth human-like movement
        act.click()                  # click with realistic dynamics
        act.type_text("hello")       # type with realistic timing
    """

    def __init__(self, monitor: int = 1) -> None:
        """
        Parameters
        ----------
        monitor : mss monitor index.
                  0 = all monitors combined (virtual desktop)
                  1 = primary monitor (usually the laptop screen)
                  2 = secondary monitor
        """
        import mss
        self._mouse = MouseController()
        self._keyboard = KeyboardController()

        # Get monitor offset for coordinate translation
        with mss.MSS() as sct:
            monitors = sct.monitors
            if monitor < len(monitors):
                self._monitor = monitors[monitor]
            else:
                self._monitor = monitors[1]  # fallback to primary

        # Offset from global coords to this monitor's local coords
        self._offset_x: int = self._monitor["left"]
        self._offset_y: int = self._monitor["top"]
        self._monitor_w: int = self._monitor["width"]
        self._monitor_h: int = self._monitor["height"]
        self._monitor_index: int = monitor

        self._last_x: float = self._mouse.position[0] - self._offset_x
        self._last_y: float = self._mouse.position[1] - self._offset_y

    # ------------------------------------------------------------------
    # Mouse
    # ------------------------------------------------------------------

    def move_to(
        self,
        target_x: float,
        target_y: float,
        mouse_emu: MouseEmulator,
        target_width: float = 20.0,
    ) -> list[MouseSample]:
        """
        Move the cursor to (target_x, target_y) following the human-like
        trajectory generated by the MouseEmulator.
        """
        samples = mouse_emu.move_to(
            target_x, target_y,
            target_width=target_width,
            from_x=self._last_x,
            from_y=self._last_y,
        )

        if not samples:
            return []

        # Execute each sample in real-time with monitor offset
        prev_t = 0.0
        for ms in samples:
            dt = ms.timestamp - prev_t
            if dt > 0:
                time.sleep(dt)
            self._mouse.position = (
                int(ms.x) + self._offset_x,
                int(ms.y) + self._offset_y,
            )
            prev_t = ms.timestamp

        self._last_x = samples[-1].x
        self._last_y = samples[-1].y
        return samples

    def click(
        self,
        x: float,
        y: float,
        mouse_emu: MouseEmulator,
        button: str = "left",
        target_width: float = 20.0,
    ) -> tuple[list[MouseSample], ClickEvent]:
        """
        Move to (x, y) and click with realistic dynamics.
        """
        # Move with human-like trajectory
        samples = self.move_to(x, y, mouse_emu, target_width)

        # Generate click dynamics
        click = mouse_emu.click_model.generate(x, y, button)
        btn = Button.left if button == "left" else Button.right

        # Ensure cursor is exactly at target (Fitts endpoint scatter can drift it)
        self._mouse.position = (int(x) + self._offset_x, int(y) + self._offset_y)

        # Stabilization — let the cursor settle before clicking
        time.sleep(0.08)

        # Press
        self._mouse.press(btn)
        # Hold for realistic duration
        hold_s = click.hold_duration_ms / 1000.0
        time.sleep(hold_s)

        # Release
        self._mouse.release(btn)

        # Small post-click pause (don't jerk away)
        time.sleep(0.04)

        self._last_x = x
        self._last_y = y
        return samples, click

    def right_click(
        self, x: float, y: float, mouse_emu: MouseEmulator, target_width: float = 20.0,
    ) -> tuple[list[MouseSample], ClickEvent]:
        """Right-click at position."""
        return self.click(x, y, mouse_emu, "right", target_width)

    def hover(
        self, x: float, y: float, mouse_emu: MouseEmulator, duration_s: float = 1.5,
    ) -> None:
        """Move to position and dwell."""
        self.move_to(x, y, mouse_emu)
        time.sleep(duration_s)
        self._last_x, self._last_y = x, y

    # ------------------------------------------------------------------
    # Keyboard
    # ------------------------------------------------------------------

    def press_key(self, key: str) -> None:
        """Press and release a single key."""
        k = self._resolve_key(key)
        self._keyboard.press(k)
        time.sleep(0.06)
        self._keyboard.release(k)

    def type_text(self, text: str, delay_ms: float = 80.0) -> None:
        """Type text with uniform delay between keystrokes."""
        for ch in text:
            self._keyboard.press(ch)
            time.sleep(0.05)
            self._keyboard.release(ch)
            time.sleep(delay_ms / 1000.0)

    def hotkey(self, modifiers: list[str], key: str) -> None:
        """Press a modifier+key combination."""
        mod_objs = [self._resolve_key(m) for m in modifiers]
        key_obj = self._resolve_key(key)

        for m in mod_objs:
            self._keyboard.press(m)
            time.sleep(0.03)
        self._keyboard.press(key_obj)
        time.sleep(0.06)
        self._keyboard.release(key_obj)
        time.sleep(0.03)
        for m in reversed(mod_objs):
            self._keyboard.release(m)

    # ------------------------------------------------------------------
    # Screen capture
    # ------------------------------------------------------------------

    def capture_screen(self) -> np.ndarray:
        """Capture the configured monitor as an HSV numpy array."""
        import os
        import cv2

        # Wayland check — mss only works on X11
        if os.environ.get("XDG_SESSION_TYPE") == "wayland":
            raise RuntimeError(
                "Screen capture does not work on Wayland.\n\n"
                "Fix: Log out → click gear icon ⚙️ → select 'Ubuntu on Xorg' → log back in.\n"
                "This is a 10-second change and fixes all screen capture tools.\n\n"
                "Wayland blocks programmatic screen capture by design — this is expected."
            )

        import mss
        with mss.MSS() as sct:
            img = np.array(sct.grab(self._monitor))
            # mss returns BGRA, convert to BGR then HSV
            bgr = cv2.cvtColor(img, cv2.COLOR_BGRA2BGR)
            hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
            return hsv

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _resolve_key(self, key: str):
        """Convert a string key name to a pynput Key object."""
        special = {
            "ctrl": Key.ctrl, "alt": Key.alt, "shift": Key.shift,
            "escape": Key.esc, "enter": Key.enter, "tab": Key.tab,
            "backspace": Key.backspace, "space": Key.space,
            "up": Key.up, "down": Key.down, "left": Key.left, "right": Key.right,
        }
        return special.get(key.lower(), key)

    def rotate_camera(self, degrees: int = 90) -> None:
        """Rotate OSRS camera by middle-mouse dragging horizontally."""
        import random
        btn = Button.middle
        cx, cy = int(self._last_x) + self._offset_x, int(self._last_y) + self._offset_y

        # Press middle button
        self._mouse.position = (cx, cy)
        time.sleep(0.05)
        self._mouse.press(btn)
        time.sleep(0.03)

        # Drag horizontally — ~3px per degree
        direction = 1 if random.random() > 0.5 else -1
        pixels = abs(degrees) * 3
        steps = 20
        for i in range(steps):
            px = cx + int(pixels * direction * i / steps)
            self._mouse.position = (px, cy)
            time.sleep(0.01)

        time.sleep(0.03)
        self._mouse.release(btn)
        time.sleep(0.1)  # let camera settle

    @property
    def mouse_position(self) -> tuple[float, float]:
        return self._last_x, self._last_y

    def monitor_info(self) -> dict:
        """Return info about the configured monitor."""
        return {
            "index": self._monitor_index,
            "width": self._monitor_w,
            "height": self._monitor_h,
            "offset_x": self._offset_x,
            "offset_y": self._offset_y,
        }

    @staticmethod
    def list_monitors() -> list[dict]:
        """List all detected monitors."""
        import mss
        with mss.MSS() as sct:
            monitors = []
            for i, m in enumerate(sct.monitors):
                monitors.append({
                    "index": i,
                    "width": m["width"],
                    "height": m["height"],
                    "left": m["left"],
                    "top": m["top"],
                    "description": (
                        "Virtual desktop (all)" if i == 0 else
                        f"Monitor {i}" + (" (primary)" if m["left"] == 0 and m["top"] == 0 else "")
                    ),
                })
        return monitors
